spring:
  application:
    name: Storehouse
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

server:
  port: 8079

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus